/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6752. Copyright MediaTek Inc. (C) 2013.
 * Fri Nov 20 16:15:00 2015
 * Do Not Modify the File.
 */

#define CUST_EINT_POLARITY_LOW              0
#define CUST_EINT_POLARITY_HIGH             1
#define CUST_EINT_EDGE_SENSITIVE            0
#define CUST_EINT_LEVEL_SENSITIVE           1




#define CUST_EINT_MD2_1_NAME             "MD2_SIM2_HOT_PLUG_EINT"
#define CUST_EINT_MD2_1_NUM              1
#define CUST_EINT_MD2_1_DEBOUNCE_CN      100
#define CUST_EINT_MD2_1_POLARITY         CUST_EINT_POLARITY_LOW
#define CUST_EINT_MD2_1_SENSITIVE        CUST_EINT_MD_LEVEL_SENSITIVE
#define CUST_EINT_MD2_1_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_ENABLE

#define CUST_EINT_MD2_CNT      1


